/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ortizsoft.view;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Fernandoi
 */
public class Menu extends javax.swing.JFrame {

    // Armazenando um tema padrão para aplicação
    // com.sun.java.swing.plaf.motif.MotifLookAndFeel
    // com.jtattoo.plaf.smat.SmartLookAndFeel
    protected static String temaEscolhido = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";

    /**
     * Construtor Padrão.
     */
    public Menu() {
        temas();
        initComponents();
        //verificarLAFs();
    }

    protected void temas() {
        try {
            UIManager.setLookAndFeel(temaEscolhido);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    /**
     * Método para verificar quais Look And Feels estão instalados.
     */
    private void verificarLAFs() {
        for (LookAndFeelInfo LAF : UIManager.getInstalledLookAndFeels()) {
            System.out.println(LAF.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem17 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        buttonCartoes = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        buttonPagamentos = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        menu_temas = new javax.swing.JMenu();
        item_mint = new javax.swing.JMenuItem();
        item_alluminium = new javax.swing.JMenuItem();
        item_mcWin = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();

        jMenuItem17.setText("jMenuItem17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OrtizSoft Sistema Comercial versão 0.1");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(229, 245, 250));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        jToolBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jToolBar1.setFloatable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/users-group.png"))); // NOI18N
        jButton1.setText("Clientes");
        jButton1.setToolTipText("Cadastro de Clientes");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/fornecedores.png"))); // NOI18N
        jButton2.setText("Fornecedores");
        jButton2.setToolTipText("Cadastro de Fornecedores");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/funcionarios.png"))); // NOI18N
        jButton3.setText("Funcionários");
        jButton3.setToolTipText("Cadastro de Funcionários");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/departamentos.png"))); // NOI18N
        jButton4.setText("Departamentos");
        jButton4.setToolTipText("Cadastro de Departamentos");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator6);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/produtos.png"))); // NOI18N
        jButton5.setText("Produtos");
        jButton5.setToolTipText("Cadastro de Produtos");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/unidade.png"))); // NOI18N
        jButton6.setText("Unidades");
        jButton6.setToolTipText("Cadastro de Unidades");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);
        jToolBar1.add(jSeparator7);

        buttonCartoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/credit-card.png"))); // NOI18N
        buttonCartoes.setText("Cartões");
        buttonCartoes.setToolTipText("Cadastro de Cartões");
        buttonCartoes.setFocusable(false);
        buttonCartoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCartoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCartoesActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonCartoes);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/increased-revenue.png"))); // NOI18N
        jButton8.setText("Plano de Contas");
        jButton8.setToolTipText("Cadastro de Planos de Contas");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton8);

        buttonPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/payment-method.png"))); // NOI18N
        buttonPagamentos.setText("Pagamentos");
        buttonPagamentos.setToolTipText("Cadastro Tipos de Pagamentos/Recebimentos");
        buttonPagamentos.setFocusable(false);
        buttonPagamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPagamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagamentosActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonPagamentos);
        jToolBar1.add(jSeparator11);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/exit.png"))); // NOI18N
        jButton10.setText("Sair");
        jButton10.setToolTipText("Sair");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(10, 0, 950, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 960, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/logo-ortiz copy.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 190, 340, 180);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/Untitled-1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 370, 470, 60);

        jMenu1.setText("Cadastro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24users-group.png"))); // NOI18N
        jMenuItem1.setMnemonic('c');
        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24man-talking-by-mic-on-a-presentation.png"))); // NOI18N
        jMenuItem2.setMnemonic('f');
        jMenuItem2.setText("Fornecedores");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24money-bag.png"))); // NOI18N
        jMenuItem3.setMnemonic('b');
        jMenuItem3.setText("Contas Bancárias");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24barcode.png"))); // NOI18N
        jMenuItem4.setMnemonic('u');
        jMenuItem4.setText("Unidades");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24product-realise.png"))); // NOI18N
        jMenuItem5.setMnemonic('p');
        jMenuItem5.setText("Produtos");
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator2);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24telephone-operator.png"))); // NOI18N
        jMenuItem6.setMnemonic('d');
        jMenuItem6.setText("Departamentos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24business-card-identification-with-clip.png"))); // NOI18N
        jMenuItem7.setMnemonic('n');
        jMenuItem7.setText("Funcionários");
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator3);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24credit-card.png"))); // NOI18N
        jMenuItem8.setMnemonic('r');
        jMenuItem8.setText("Cartões");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24increased-revenue.png"))); // NOI18N
        jMenuItem9.setMnemonic('o');
        jMenuItem9.setText("Plano de Contas");
        jMenuItem9.setToolTipText("t");
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24payment-method.png"))); // NOI18N
        jMenuItem10.setMnemonic('T');
        jMenuItem10.setText("Tipos de Pagamentos/Recebimentos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);
        jMenu1.add(jSeparator4);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24exit.png"))); // NOI18N
        jMenuItem11.setMnemonic('S');
        jMenuItem11.setText("Sair");
        jMenuItem11.setToolTipText("a");
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimento");

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24dollar-bill.png"))); // NOI18N
        jMenuItem12.setMnemonic('p');
        jMenuItem12.setText("Contas a Pagar");
        jMenu2.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24money.png"))); // NOI18N
        jMenuItem13.setMnemonic('r');
        jMenuItem13.setText("Contas a Receber");
        jMenu2.add(jMenuItem13);
        jMenu2.add(jSeparator8);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24commerce.png"))); // NOI18N
        jMenuItem16.setMnemonic('v');
        jMenuItem16.setText("Vendas");
        jMenu2.add(jMenuItem16);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24commerce-1.png"))); // NOI18N
        jMenu6.setMnemonic('c');
        jMenu6.setText("Compras");

        jMenuItem18.setText("Requisição");
        jMenu6.add(jMenuItem18);

        jMenuItem19.setText("Cotação");
        jMenu6.add(jMenuItem19);

        jMenuItem20.setText("Confirmar Cotação");
        jMenu6.add(jMenuItem20);

        jMenuItem21.setText("Pedido");
        jMenu6.add(jMenuItem21);

        jMenu2.add(jMenu6);
        jMenu2.add(jSeparator9);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24cardboard-box-with-glasses.png"))); // NOI18N
        jMenu5.setMnemonic('E');
        jMenu5.setText("Controle de Estoque");

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/notepad.png"))); // NOI18N
        jMenuItem14.setText("Entrada de NF");
        jMenu5.add(jMenuItem14);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/currency-value.png"))); // NOI18N
        jMenuItem15.setText("Atualização de Preços");
        jMenu5.add(jMenuItem15);

        jMenu2.add(jMenu5);
        jMenu2.add(jSeparator10);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24coins-stacks-and-banknotes.png"))); // NOI18N
        jMenu7.setMnemonic('t');
        jMenu7.setText("Tesouraria e Banco");

        jMenuItem22.setText("Emissão de Cheques");
        jMenu7.add(jMenuItem22);

        jMenuItem23.setText("Conciliação de Cheques");
        jMenu7.add(jMenuItem23);

        jMenuItem24.setText("Movimento de Banco");
        jMenu7.add(jMenuItem24);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Utilitários");

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortizsoft/view/imagens/24calculator.png"))); // NOI18N
        jMenuItem25.setText("Calculadora");
        jMenu3.add(jMenuItem25);

        jMenuItem26.setText("Calendário");
        jMenu3.add(jMenuItem26);
        jMenu3.add(jSeparator5);

        jMenu8.setText("Sistema de Segurança");

        jMenuItem28.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem28.setText("Trocar Senha Corrente");
        jMenu8.add(jMenuItem28);

        jMenuItem29.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem29.setText("Definir Nível de Acesso");
        jMenu8.add(jMenuItem29);

        jMenu3.add(jMenu8);

        menu_temas.setText("Personalizar Temas");

        item_mint.setText("Mint Tema");
        item_mint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_mintActionPerformed(evt);
            }
        });
        menu_temas.add(item_mint);

        item_alluminium.setText("Aluminium Tema");
        item_alluminium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_alluminiumActionPerformed(evt);
            }
        });
        menu_temas.add(item_alluminium);

        item_mcWin.setText("McWin Tema");
        item_mcWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_mcWinActionPerformed(evt);
            }
        });
        menu_temas.add(item_mcWin);

        jMenu3.add(menu_temas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        jMenuItem27.setText("Sobre o Sistema");
        jMenu4.add(jMenuItem27);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(981, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Cartões";
        CartaoView.main(args);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void buttonCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCartoesActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Cartões";
        CartaoView.main(args);
    }//GEN-LAST:event_buttonCartoesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Clientes";
        ClientesView.main(args);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Evento para cadastro de conta bancária.
     *
     * @param evt
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro das Contas Bancárias";
        BancoView.main(args);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Tipos de Pagamentos/Recebimentos";
        TipoPagamentoView.main(args);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void buttonPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagamentosActionPerformed
        String args[] = new String[1];
        args[0] = "Cadastro de Tipos de Pagamentos/Recebimentos";
        TipoPagamentoView.main(args);
    }//GEN-LAST:event_buttonPagamentosActionPerformed

    private void item_mintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_mintActionPerformed
        temaEscolhido = "com.jtattoo.plaf.mint.MintLookAndFeel";
        temas();
    }//GEN-LAST:event_item_mintActionPerformed

    private void item_alluminiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_alluminiumActionPerformed
        temaEscolhido = "com.jtattoo.plaf.aluminium.AluminiumLookAndFeel";
        temas();
    }//GEN-LAST:event_item_alluminiumActionPerformed

    private void item_mcWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_mcWinActionPerformed
        temaEscolhido = "com.jtattoo.plaf.bernstein.BernsteinLookAndFeel";
        temas();
    }//GEN-LAST:event_item_mcWinActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCartoes;
    private javax.swing.JButton buttonPagamentos;
    private javax.swing.JMenuItem item_alluminium;
    private javax.swing.JMenuItem item_mcWin;
    private javax.swing.JMenuItem item_mint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menu_temas;
    // End of variables declaration//GEN-END:variables
}
